Dbp 352 set the correct docker image in the helm chart for each spsh repository (#8)
* Update chart-release.yaml for release 2.1.1

* Add changes in DBP-340-trivy

* Update chart-release.yaml for release 2.1.1

* Your commit message

* Update appVersion in Chart.yaml

* Generate Docker metadata, Update appVersion in Chart.yaml, Update chart-release.yaml for release 2.1.1

* Adjust images & Update chart-release.yaml for release 2.1.1

* Adjust images & Update chart-release.yaml for release 2.1.1

* Adjust images & set tag im chart.yaml & Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* Update chart-release.yaml for release 2.1.1

* push to main

* Determine Docker Tag using tag-generation

* Determine Docker Tag

* use tag_generation as docker tag

* use tag generation for docker tag

* use tag generation as docker tag

* use tag generation as docker tag

* Determine Docker Tag

* Trivy explanation to avoid branch conflict

* Set tag_generation to always be one of the specified values: 'ticket_from_branch', 'commit_hash', or 'specified'

* If the regex doesn't match (meaning no ticket number is found in the branch name), it logs an error message and exits the job with a non-zero status (exit 1)

diff --git a/.github/workflows/chart-release.yaml b/.github/workflows/chart-release.yaml
--- a/.github/workflows/chart-release.yaml
+++ b/.github/workflows/chart-release.yaml
@@ -32,6 +32,17 @@ on:
         description: "Replace placeholders before chart packaging. Defined as sed command (optional)."
         required: false
         default: ""
+      tag_generation:
+        description: "Generation of the image tag: ticket_from_branch(default), commit_hash or version_git_tag, specified"
+        required: false
+        type: string
+        default: "ticket_from_branch"
+      image_tag:
+        type: string
+        description: "image tag (required if tag_generation: specified)"
+        required: false
+        
+
 jobs:
   release:
     runs-on: ubuntu-latest
@@ -86,9 +97,26 @@ jobs:
         run: |
           echo "chart_version=${{ inputs.chart_version }}" >> $GITHUB_ENV
 
+      - name: Determine Image Tag
+        run: |
+          if [[ "${{ inputs.tag_generation }}" == 'ticket_from_branch' ]]; then
+            regex='^([[:alpha:]]+?-[[:digit:]]+)'
+            if [[ $GITHUB_REF_NAME =~ $regex ]]; then
+              image_tag="${BASH_REMATCH[1]}"
+            else
+            echo "::error::Couldn't extract ticket from branch $GITHUB_REF_NAME. The branch name should begin with a ticket (e.g. SPSH-1234-test-name)"
+              exit 1
+            fi
+          elif [[ "${{ inputs.tag_generation }}" == 'commit_hash' ]]; then
+            image_tag="sha-$(echo ${GITHUB_SHA} | cut -c1-8)"
+          elif [[ "${{ inputs.tag_generation }}" == 'specified' ]]; then
+            image_tag="${{ inputs.image_tag }}"
+          fi
+          echo "image_tag=$image_tag" >> $GITHUB_ENV
+
       - name: Prepare Helm Chart
         run:  |
-          helm package ${{ inputs.chart_path }}/${{ inputs.chart_name }} -d helm-charts-registry ${{ inputs.version_generation != 'chart_yaml' && '--version $chart_version' }}
+          helm package ${{ inputs.chart_path }}/${{ inputs.chart_name }} -d helm-charts-registry --app-version ${{ env.image_tag }} ${{ inputs.version_generation != 'chart_yaml' && '--version $chart_version' || '' }}
           cd helm-charts-registry
           if [ -d "automation/${{ inputs.chart_name }}" ]; then rm -r automation/${{ inputs.chart_name }}; fi
           tar -xzf ${{ inputs.chart_name }}*.tgz
@@ -103,4 +131,4 @@ jobs:
           cd helm-charts-registry/automation
           git add ${{ inputs.chart_name }}
           git commit -m "${{ inputs.chart_name }}"
-          git push origin main
+          git push origin main  
