feat(nest-lint): DBP-2321 Update node versions (#55)
* feat(nest-lint): Option to setup node via version_file

* chore(deps): Bump checkout action version

diff --git a/.github/workflows/check-nest-lint.yaml b/.github/workflows/check-nest-lint.yaml
--- a/.github/workflows/check-nest-lint.yaml
+++ b/.github/workflows/check-nest-lint.yaml
@@ -5,13 +5,32 @@ on:
     inputs:
       node_version:
         type: string
-        description: "Version to use for node"
-        required: true
+        description: "Version to use for node. Takes precedence over version_file."
+        required: false
+      node_version_file:
+        type: string
+        description: "File containing the node version (e.g. package.json)."
+        required: false
 
 env:
   NODE_VERSION: ${{ inputs.node_version }}
-
+  NODE_VERSION_FILE: ${{ inputs.node_version_file }}
 jobs:
+  
+  validate_inputs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate inputs
+        shell: bash
+        run: |
+          node_version="${{ inputs.node_version }}"
+          node_version_file="${{ inputs.node_version_file }}"
+
+          if [[ -z "$node_version" && -z "$node_version_file" ]]; then
+            echo "::error::You must provide at least one of: node_version or node_version_file"
+            exit 1
+          fi
+
   nest_lint:
     name: Nest Lint
     runs-on: ubuntu-latest
@@ -20,12 +39,13 @@ jobs:
     timeout-minutes: 5
     steps:
       - name: Checkout repository
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  #v4.1.1
+        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  #v6.0.3
 
       - name: Setup node
-        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 #v4.0.2
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
         with:
           node-version: ${{ env.NODE_VERSION }}
+          node-version-file: ${{ env.NODE_VERSION_FILE }}
 
       - name: Install dependencies
         run: npm ci --prefer-offline --no-audit
