fix

diff --git a/.github/workflows/image-publish-trivy.yaml b/.github/workflows/image-publish-trivy.yaml
--- a/.github/workflows/image-publish-trivy.yaml
+++ b/.github/workflows/image-publish-trivy.yaml
@@ -120,6 +120,16 @@ jobs:
       packages: write
       contents: read
     steps:
+      - name: Check conditional inputs
+        run: |
+          if [[ ${{ contains(inputs.container_registry, 'dockerhub') }} && -z inputs.dockerhub_repository_owner ]]; then
+            echo "Error: when pushing to dockerhub a repository owner is required."
+            exit 1
+          elif [[ ${{ contains(inputs.container_registry, 'quay.io') }} && -z inputs.quay_repository_owner ]]; then
+            echo "Error: when pushing to quay.io a repository owner is required."
+            exit 1
+          fi
+
       - name: Checkout Code
         if: ${{ inputs.code_source == 'checkout' }}
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
@@ -133,16 +143,6 @@ jobs:
       # see https://github.com/actions/upload-artifact#permission-loss
       - name: Extract code artifact
         run: tar -xvf build-code.tar -C .
-
-      - name: Check conditional inputs
-        run: |
-          if [[ ${{ contains(inputs.container_registry, 'dockerhub') }} && -z inputs.dockerhub_repository_owner ]]; then
-            echo "Error: when pushing to dockerhub a repository owner is required."
-            exit 1
-          elif [[ ${{ contains(inputs.container_registry, 'quay.io') }} && -z inputs.quay_repository_owner ]]; then
-            echo "Error: when pushing to quay.io a repository owner is required."
-            exit 1
-          fi
 
       - name: Build image name and tags
         id: docker_meta_img
